### ISSUE TITLE
Error: The process '/usr/bin/git' failed with exit code 128 

### ISSUE THREAD

**Issue by AdamBebko** [yoichiro/gh-action-increment-value#5]
Hello, First off, thanks for such a great tool. We've been using it for several months now and it's really helped our workflow.

Yesterday a new error just popped up when running it:

```
Target file: build-number.json
[9](https://github.com/secretlocation/dps-learnwithpeppa-app/actions/runs/3742429379/jobs/6353359895#step:5:10)
Incremented the value from 206 to 207.
[10](https://github.com/secretlocation/dps-learnwithpeppa-app/actions/runs/3742429379/jobs/6353359895#step:5:11)
/usr/bin/git config user.name Automated Increment value
[11](https://github.com/secretlocation/dps-learnwithpeppa-app/actions/runs/3742429379/jobs/6353359895#step:5:12)
fatal: not in a git directory
[12](https://github.com/secretlocation/dps-learnwithpeppa-app/actions/runs/3742429379/jobs/6353359895#step:5:13)
✖  fatal     Error: The process '/usr/bin/git' failed with exit code 128 
[13](https://github.com/secretlocation/dps-learnwithpeppa-app/actions/runs/3742429379/jobs/6353359895#step:5:14)
    at ExecState._setResult (/node_modules/@actions/exec/lib/toolrunner.js:592:25)
[14](https://github.com/secretlocation/dps-learnwithpeppa-app/actions/runs/3742429379/jobs/6353359895#step:5:15)
    at ExecState.CheckComplete (/node_modules/@actions/exec/lib/toolrunner.js:575:18)
[15](https://github.com/secretlocation/dps-learnwithpeppa-app/actions/runs/3742429379/jobs/6353359895#step:5:16)
    at ChildProcess.<anonymous> (/node_modules/@actions/exec/lib/toolrunner.js:469:27)
[16](https://github.com/secretlocation/dps-learnwithpeppa-app/actions/runs/3742429379/jobs/6353359895#step:5:17)
    at ChildProcess.emit (node:events:527:28)
[17](https://github.com/secretlocation/dps-learnwithpeppa-app/actions/runs/3742429379/jobs/6353359895#step:5:18)
    at maybeClose (node:internal/child_process:1092:16)
[18](https://github.com/secretlocation/dps-learnwithpeppa-app/actions/runs/3742429379/jobs/6353359895#step:5:19)
    at Socket.<anonymous> (node:internal/child_process:451:11)
[19](https://github.com/secretlocation/dps-learnwithpeppa-app/actions/runs/3742429379/jobs/6353359895#step:5:20)
    at Socket.emit (node:events:527:28)
[20](https://github.com/secretlocation/dps-learnwithpeppa-app/actions/runs/3742429379/jobs/6353359895#step:5:21)
    at Pipe.<anonymous> (node:net:709:12)
[21](https://github.com/secretlocation/dps-learnwithpeppa-app/actions/runs/3742429379/jobs/6353359895#step:5:22)
✖  fatal     Failed to increment the value.
```

Here is our checkout step:

```yml
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
        token: ${{ secrets.GH_TOKEN }} # must have admin permissions to repo
```

secrets.GH_TOKEN is a personal access token with all privileges checked. I regenerated it just to be sure.

Here is our step where we auto increment:

```yml
   - name: Increment build in build-number.json 
      if: steps.semantic.outputs.new_release_published == 'true'
      uses: yoichiro/gh-action-increment-value@main
      with:
        target_file: 'build-number.json'
        prefix: 'buildNumber":'
        suffix: '}'
        commit_message: 'Increment the build number to'
    
```

Any ideas on what might be going wrong? Again, this was working perfectly for several months, and just broke yesterday (dec 19)

**Comment by yoichiro** [comment]
@AdamBebko Thank you for reporting this issue. I'm also facing this issue and now investigating.

**Comment by yoichiro** [comment]
@AdamBebko I have fixed this issue. When re-running your job, currently it should work normally. Could you do that? Thanks.

**Comment by AdamBebko** [comment]
Thanks so much, I'll try tomorrow and report back.

**Comment by AdamBebko** [comment]
Sorry for the delay, had to switch gears for a bit on the project. Unfortunately, still getting an error.

```
error: failed to push some refs to 'https://github.com/secretlocation/dps-learnwithpeppa-app.git'
[25](https://github.com/secretlocation/dps-learnwithpeppa-app/actions/runs/3952969033/jobs/6768695241#step:5:26)
✖  fatal     Error: The process '/usr/bin/git' failed with exit code 1 
[26](https://github.com/secretlocation/dps-learnwithpeppa-app/actions/runs/3952969033/jobs/6768695241#step:5:27)
    at ExecState._setResult (/node_modules/@actions/exec/lib/toolrunner.js:592:25)
[27](https://github.com/secretlocation/dps-learnwithpeppa-app/actions/runs/3952969033/jobs/6768695241#step:5:28)
    at ExecState.CheckComplete (/node_modules/@actions/exec/lib/toolrunner.js:575:18)
[28](https://github.com/secretlocation/dps-learnwithpeppa-app/actions/runs/3952969033/jobs/6768695241#step:5:29)
    at ChildProcess.<anonymous> (/node_modules/@actions/exec/lib/toolrunner.js:469:27)
[28](https://github.com/secretlocation/dps-learnwithpeppa-app/actions/runs/3952969033/jobs/6768695241#step:5:29)
    at ChildProcess.emit (node:events:513:28)
[29](https://github.com/secretlocation/dps-learnwithpeppa-app/actions/runs/3952969033/jobs/6768695241#step:5:30)
    at maybeClose (node:internal/child_process:1098:16)
[30](https://github.com/secretlocation/dps-learnwithpeppa-app/actions/runs/3952969033/jobs/6768695241#step:5:31)
    at ChildProcess._handle.onexit (node:internal/child_process:304:5)
[31](https://github.com/secretlocation/dps-learnwithpeppa-app/actions/runs/3952969033/jobs/6768695241#step:5:32)
✖  fatal     Failed to increment the value.
```

same scripts as above.


our file looks like this (build-number.json).

`{"buildNumber":211}`

**Comment by yoichiro** [comment]
@AdamBebko Hmm... Could you give me more log? I would like to confirm more output of before and after the log output above.

**Comment by yoichiro** [comment]
@AdamBebko Well, the output `failed to push some refs to` means it cannot be merged to the remote branch because the remote branch has already been gone forward than the source branch. But, I'm not sure that this situation occurd.

In addition, could you test the following?
* Use `actions/checkout@v3` instead of `actions/checkout@v2`.
* Reissue the personal access token (named `GH_TOKEN`).

**Comment by AdamBebko** [comment]
I looked into the logs a bit deeper, I found some issues with git LFS. is it possible that your script is not loading git LFS, so when it tries to commit the changes, this error occurs?


```
Target file: build-number.json
[9](https://github.com/secretlocation/dps-learnwithpeppa-app/actions/runs/3960642622/jobs/6785066319#step:5:10)
Incremented the value from 212 to 213.
[10](https://github.com/secretlocation/dps-learnwithpeppa-app/actions/runs/3960642622/jobs/6785066319#step:5:11)
/usr/bin/git config user.name Automated Increment value
[11](https://github.com/secretlocation/dps-learnwithpeppa-app/actions/runs/3960642622/jobs/6785066319#step:5:12)
/usr/bin/git config user.email gh-action-increment-value@users.noreply.github.com
[12](https://github.com/secretlocation/dps-learnwithpeppa-app/actions/runs/3960642622/jobs/6785066319#step:5:13)
Current branch: develop
[13](https://github.com/secretlocation/dps-learnwithpeppa-app/actions/runs/3960642622/jobs/6785066319#step:5:14)
/usr/bin/git commit -a -m ci: Increment the build number to 213
[14](https://github.com/secretlocation/dps-learnwithpeppa-app/actions/runs/3960642622/jobs/6785066319#step:5:15)

[15](https://github.com/secretlocation/dps-learnwithpeppa-app/actions/runs/3960642622/jobs/6785066319#step:5:16)
This repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting '.git/hooks/post-commit'.
[16](https://github.com/secretlocation/dps-learnwithpeppa-app/actions/runs/3960642622/jobs/6785066319#step:5:17)

[17](https://github.com/secretlocation/dps-learnwithpeppa-app/actions/runs/3960642622/jobs/6785066319#step:5:18)
[develop 49ce66d3] ci: Increment the build number to 213
[18](https://github.com/secretlocation/dps-learnwithpeppa-app/actions/runs/3960642622/jobs/6785066319#step:5:19)
 1 file changed, 1 insertion(+), 1 deletion(-)
[19](https://github.com/secretlocation/dps-learnwithpeppa-app/actions/runs/3960642622/jobs/6785066319#step:5:20)
/usr/bin/git push ***github.com/secretlocation/dps-learnwithpeppa-app.git
[20](https://github.com/secretlocation/dps-learnwithpeppa-app/actions/runs/3960642622/jobs/6785066319#step:5:21)

[21](https://github.com/secretlocation/dps-learnwithpeppa-app/actions/runs/3960642622/jobs/6785066319#step:5:22)
This repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting '.git/hooks/pre-push'.
[22](https://github.com/secretlocation/dps-learnwithpeppa-app/actions/runs/3960642622/jobs/6785066319#step:5:23)
```

**Comment by yoichiro** [comment]
@AdamBebko Well, I don't have an experience to use the git LFS. Therefore, when I developed this Github Actions, I didn't care that, and I don't have any knowledge how to make the git LFS available. That is, this action installs the git only:

https://github.com/yoichiro/gh-action-increment-value/blob/main/Dockerfile#L11

If I add the git-lfs package to this action using `sudo apt-get install git-lfs` in the Dockerfile, do you think that your issue can be fixed?

**Comment by AdamBebko** [comment]
Thanks for your persistence I appreciate it. 

Yes I think that maybe if you install git lfs right after git, it might fix the issue.

**Comment by yoichiro** [comment]
@AdamBebko I have added the `git-lfs` into the package list of `apt install` command. This modification has already been merged into the main branch. Could you test with the main branch whether this works normally on your Github repository?

**Comment by AdamBebko** [comment]
@yoichiro  Thanks so much, I will report back here next time we run our scripts!

**Comment by AdamBebko** [comment]
It worked perfectly. Thanks so much for the fix! Really appreciate your time, and your excellent scripts!

**Comment by yoichiro** [comment]
@AdamBebko Great! Thank you for your feedback!
